import React from 'react';
import { Settings, ShieldCheck, Database, FileText, CheckCircle2, Info, Server, Cpu } from 'lucide-react';

export default function SettingsView({ casesCount = 0 }) {
  return (
    <div className="space-y-6 max-w-5xl mx-auto text-xs">
      
      <div>
        <h2 className="text-xl font-black text-slate-900 tracking-tight">
          System Configuration & Platform Settings
        </h2>
        <p className="text-slate-500 mt-0.5">
          Architecture specifications, evidence standards alignment, and local database telemetry.
        </p>
      </div>

      {/* Specification Card */}
      <div className="p-6 rounded-2xl bg-white border border-slate-200 shadow-2xs space-y-4">
        <div className="flex items-center gap-2.5 border-b border-slate-100 pb-3">
          <div className="p-2 rounded-xl bg-blue-50 text-blue-600">
            <ShieldCheck className="w-5 h-5" />
          </div>
          <div>
            <h3 className="text-sm font-bold text-slate-900">
              AICTE Problem Statement ID: 26106
            </h3>
            <p className="text-[11px] text-slate-500">
              AI-Powered Email Threat Detection, GeoLocation & Forensic Intelligence Platform
            </p>
          </div>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
          <div className="p-4 rounded-xl bg-slate-50 border border-slate-200 space-y-1">
            <span className="text-[10px] font-bold uppercase text-slate-400 block">Standards Alignment</span>
            <span className="font-semibold text-slate-800 text-xs block">
              Aligned with relevant digital-evidence handling principles (ISO/IEC 27037)
            </span>
            <p className="text-[11px] text-slate-500 pt-1">
              Deterministic evidence collection, byte-level raw preservation, and SHA-256 acquisition hashing.
            </p>
          </div>

          <div className="p-4 rounded-xl bg-slate-50 border border-slate-200 space-y-1">
            <span className="text-[10px] font-bold uppercase text-slate-400 block">Local Data Persistence</span>
            <span className="font-semibold text-slate-800 text-xs block">
              SQLite (Single Embedded Database)
            </span>
            <p className="text-[11px] text-slate-500 pt-1">
              Transactional integrity, foreign keys, and zero external cloud database dependencies.
            </p>
          </div>

          <div className="p-4 rounded-xl bg-slate-50 border border-slate-200 space-y-1">
            <span className="text-[10px] font-bold uppercase text-slate-400 block">Investigative Pipeline Status</span>
            <span className="font-semibold text-emerald-700 text-xs flex items-center gap-1.5">
              <CheckCircle2 className="w-3.5 h-3.5" /> Deterministic Forensic Engine Active
            </span>
            <p className="text-[11px] text-slate-500 pt-1">
              Evidence-first rule execution: Evidence &rarr; Findings &rarr; Heuristic Risk &rarr; AI Advisory.
            </p>
          </div>

          <div className="p-4 rounded-xl bg-slate-50 border border-slate-200 space-y-1">
            <span className="text-[10px] font-bold uppercase text-slate-400 block">Offline Capability</span>
            <span className="font-semibold text-blue-700 text-xs block">
              Air-Gapped / Isolated Ready
            </span>
            <p className="text-[11px] text-slate-500 pt-1">
              Standalone HTML exports contain no CDN dependencies and operate completely offline.
            </p>
          </div>
        </div>
      </div>

      {/* Disclaimers & Legal Notice */}
      <div className="p-5 rounded-2xl bg-amber-50/70 border border-amber-200 text-amber-950 space-y-2 leading-relaxed">
        <div className="flex items-center gap-2 font-bold text-xs uppercase tracking-wider text-amber-900">
          <Info className="w-4 h-4 text-amber-700 shrink-0" />
          <span>Defensible Terminology & Legal Boundaries</span>
        </div>
        <p className="text-[11px] text-amber-900">
          Reports generated by AegisMail are designated as <strong>Tamper-Evident Forensic Reports</strong>. AegisMail does not assert automatic legal court-admissibility or formal ISO certification. SHA-256 integrity digests serve as cryptographic integrity seals and do not represent asymmetric public/private-key digital signatures.
        </p>
      </div>

    </div>
  );
}
